import type { Metadata } from "next";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import NavigationMenu from "@/components/shared/NavigationMenu";

const primaryFont = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-PrimaryFont",
});

const secondaryFont = Inter({
  subsets: ["latin"],
  variable: "--font-SecondaryFont",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${primaryFont.variable} ${secondaryFont.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <NavigationMenu/>
        <main>
          {children}
        </main>


      </body>
    </html>
  );
}
